// Computes the data-segment offset of every label in restunts' dseg.asm and
// writes src/dseg-labels.js. The bytes themselves are read from game.exe at runtime.
// usage: node tools/dseg-labels.mjs ref/restunts/src/restunts/asm/dseg.asm
import { readFileSync, writeFileSync } from 'node:fs';

const SIZES = { db: 1, dw: 2, dd: 4 };
const lines = readFileSync(process.argv[2], 'latin1').split(/\r?\n/);
const labels = {}, widths = {};
let ofs = 0, inSeg = false;
for (const raw of lines) {
  const line = raw.replace(/;.*/, '');
  if (/^dseg segment/.test(line)) { inSeg = true; continue; }
  if (!inSeg) continue;
  const m = line.match(/^([A-Za-z_0-9@?$]+)?\s+(db|dw|dd)\s+(.*)$/);
  if (!m) continue;
  if (m[1]) { labels[m[1]] = ofs; widths[m[1]] = SIZES[m[2]]; }
  ofs += SIZES[m[2]] * m[3].split(',').length;
}
// Self-check: IDA's auto-named labels encode their linear address; dseg starts at 0x3B770.
let bad = 0;
for (const [k, v] of Object.entries(labels)) {
  const a = k.match(/^(?:unk|byte|word|dword|off|stru|asc|a)_([0-9A-F]{5})$/);
  if (a && parseInt(a[1], 16) - 0x3B770 !== v) bad++;
}
if (bad) throw new Error(`${bad} labels disagree with their address`);
writeFileSync(new URL('../src/dseg-labels.js', import.meta.url),
  '// Generated by tools/dseg-labels.mjs: label -> [offset in the game.exe data segment, declared width].\nexport default ' +
  JSON.stringify(Object.fromEntries(Object.entries(labels).map(([k, v]) => [k, [v, widths[k]]]))) + ';\n');
console.log(Object.keys(labels).length, 'labels, dseg size', ofs);
