// Maps every proc/label in restunts' asmorig listings to its linear address in GAME.EXE
// (loaded at segment 0x1000, like IDA). Walks the listing in step with the real bytes,
// using the interpreter's instruction-length decoder; IDA's address-named labels self-check.
// usage: node tools/procmap.mjs ref/restunts/src/restunts/asmorig   (writes src/procs.js)
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { CPU } from '../src/x86.js';
import { M, loadExe } from '../src/mem.js';

const dir = process.argv[2];
loadExe(new Uint8Array(readFileSync(new URL('../game/GAME.EXE', import.meta.url))));
const cpu = new CPU(M);
const SIZES = { db: 1, dw: 2, dd: 4 };
const DIRECTIVES = /^(smart|nosmart|public|assume|include|extrn|align|org|even|end|\.model|nosmart|[a-z_0-9]+\s+=)/i;
const out = {};
let addr = 0x10000, resyncs = 0, smart = false;
const files = readdirSync(dir).filter(f => /^seg\d+\.asm$/.test(f)).sort();
for (const f of files) {
  for (const raw of readFileSync(`${dir}/${f}`, 'latin1').split(/\r?\n/)) {
    const line = raw.replace(/;.*/, '').trimEnd();
    if (!line.trim()) continue;
    // TASM 'smart' blocks: the listing pads with nop lines that aren't in the binary.
    if (/^smart\b/.test(line)) { smart = true; continue; }
    if (/^nosmart\b/.test(line)) { smart = false; continue; }
    if (smart && /^\s+nop\b/.test(line)) continue;
    let m;
    if ((m = line.match(/^([A-Za-z_0-9@?$]+)\s+proc\b/))) { out[m[1]] = addr; continue; }
    if ((m = line.match(/^(seg\d+)\s+segment\b/))) { out[m[1]] = addr; continue; }
    if (/^\S+\s+(endp|ends)\b/.test(line)) continue;
    if ((m = line.match(/^([A-Za-z_0-9@?$]+):(.*)$/))) {
      const a = m[1].match(/_([0-9A-F]{5})$/);
      if (a && parseInt(a[1], 16) !== addr) { resyncs++; console.error(`${f}: ${m[1]} at ${addr.toString(16)}`); addr = parseInt(a[1], 16); }
      out[m[1]] = addr;
      if (!m[2].trim()) continue;
    }
    const body = line.replace(/^([A-Za-z_0-9@?$]+):/, '').trim();
    if (DIRECTIVES.test(body)) continue;
    if ((m = body.match(/^(?:([A-Za-z_0-9@?$]+)\s+)?(db|dw|dd)\s+(.*)$/))) {
      if (m[1]) out[m[1]] = addr;
      addr += SIZES[m[2]] * m[3].split(',').length;
      continue;
    }
    addr += cpu.length(addr);
  }
}
console.error('procs:', Object.keys(out).length, 'resyncs:', resyncs, 'end', addr.toString(16));
const keep = Object.entries(out).filter(([k]) => !/^(loc|locret|off|byte|word|dword|unk|stru|asc|j)_[0-9A-F]+$/i.test(k));
writeFileSync(new URL('../src/procs.js', import.meta.url),
  '// Generated by tools/procmap.mjs: GAME.EXE function / segment linear addresses (loaded at 0x10000).\nexport default ' +
  JSON.stringify(Object.fromEntries(keep)) + ';\n');
